# Generated by Django 4.2.29 on 2026-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='sha256_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
